// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql"
)

type Post struct {
	ID        int64
	Title     string
	Content   sql.NullString
	Author    sql.NullString
	Slug      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
